version: "3.5"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  bcc-node:
    image: tbco/bcc-node:${BCC_NODE_VERSION:-1.29.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
  bcc-db-sync:
    image: tbco/bcc-db-sync:${BCC_DB_SYNC_VERSION:-11.0.0}
    command: [
      "--config", "/config/bcc-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--state-dir", "/data"
    ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - bcc-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ../config/network/${NETWORK:-mainnet}:/config
      - db-sync-data:/data
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  bcc-rosetta-server:
    build:
      cache_from:
        - tbco/bcc-rosetta:master
      context: ..
      target: bcc-rosetta-server
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BCC_CLI_PATH=/usr/local/bin/bcc-cli
      - BCC_NODE_PATH=/usr/local/bin/bcc-node
      - BCC_NODE_SOCKET_PATH=/node-ipc/node.socket
      - DB_CONNECTION_STRING=postgresql://postgres:notForProduction!@postgres:5432/cexplorer
      - DEFAULT_RELATIVE_TTL=1000
      - GENESIS_SOPHIE_PATH=/config/genesis/sophie.json
      - LOGGER_LEVEL=debug
      - PAGE_SIZE=30
      - PORT=8080
      - TOPOLOGY_FILE_PATH=/config/bcc-node/topology.json
    expose:
      - 8080
    ports:
      - ${PORT:-8080}:8080
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ../config/network/${NETWORK:-mainnet}:/config
      - node-ipc:/node-ipc
secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user
volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:
